Fix `GRAALVM_HOME`.

diff --git a/.github/actions/setup-oracle-graalvm-ea-build/action.yml b/.github/actions/setup-oracle-graalvm-ea-build/action.yml
--- a/.github/actions/setup-oracle-graalvm-ea-build/action.yml
+++ b/.github/actions/setup-oracle-graalvm-ea-build/action.yml
@@ -13,18 +13,22 @@ runs:
     - name: Set up GRAALVM_HOME with EA build
       shell: bash
       run: |
-        FILE_NAME="graalvm-jdk.tar.gz"
+        FILE_NAME="${{ github.workspace }}/graalvm.tar.gz"
         DOWNLOAD_URL=$(jq -r '(.download_base_url + (.files[] | select(.arch == "x64" and .platform == "linux") | .filename))' versions/latest-ea.json)
         echo "Downloading '${DOWNLOAD_URL}'..."
-        pushd $HOME > /dev/null
         curl --fail --silent --location --retry 3 --max-time 10 --output "${FILE_NAME}" --request GET "${DOWNLOAD_URL}"
-        tar xzf "${FILE_NAME}"
-        GRAALVM_HOME=$(find $(pwd) -type d -name "graalvm-jdk-*")
-        echo "GRAALVM_HOME=${GRAALVM_HOME}" >> ${GITHUB_ENV}
-        popd > /dev/null
+        tar xzf "${FILE_NAME}" -C ${{ github.workspace }}
+        GRAALVM_HOME=$(find "${{ github.workspace }}" -type d -name "graalvm-*")
+        if [ -d "${GRAALVM_HOME}" ]; then
+          echo "GRAALVM_HOME=${GRAALVM_HOME}"
+          echo "GRAALVM_HOME=${GRAALVM_HOME}" >> ${GITHUB_ENV}
+        else
+          echo "Could not determine GRAALVM_HOME (set to '${GRAALVM_HOME}')"
+          exit 1
+        fi
     - name: Set up JAVA_HOME
       if: ${{ inputs.java-version }} != ''
-      uses: actions/setup-java@v4
+      uses: actions/setup-java@v5
       with:
         distribution: 'oracle'
         java-version: '${{ inputs.java-version }}'
